[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1
via-ir = true
remappings = []

[fuzz]
runs = 1000
max_test_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]

[invariant]
runs = 256
depth = 32
fail_on_revert = true

[etherscan]
sepolia = { key = "${ETHERSCAN_SEPOLIA_API_KEY}" }
optimism_sepolia = { key = "${ETHERSCAN_OPTIMISM_API_KEY}" }
arbitrum_sepolia = { key = "${ETHERSCAN_ARBITRUM_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_BASE_API_KEY}" }

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
optimism_sepolia = "https://optimism-sepolia-rpc.publicnode.com"
arbitrum_sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
