name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1.2.0

      - name: Install Node.js and Lcov
        run: sudo apt update && sudo apt install nodejs lcov -y

      - name: Run npm install
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run static analysis
        run: npm run analyze
